spring.application.name=email

server.port=8082


spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://yuumxntf:msaba23a7Od2DP8zkV5izb5XAWPkl3p_@chimpanzee.rmq.cloudamqp.com/yuumxntf
broker.queue.email.name=default.email


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=recalculos29@gmail.com
spring.mail.password=jjms eihi zmhq onbr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

